name: workflow_example
on: workflow_dispatch
jobs:
  first_job:
    runs-on:  ubuntu-latest
    steps:
      - name: First step
        run: echo "First step"
      - name: second step
        run: echo "Second step"
  python_example:
    runs-on: ubuntu-latest
    steps:
      - name: Download the code
        uses: actions/checkout@v3
      - name: Run python code
        run: python test.py
      - name: Listing file
        run: ls /
      - name: print current wrk dir
        run: pwd
      - name: Python location
        run: which test.py
