name: workflow_example
on: workflow_dispatch
jobs:
  first_job:
    runs-on:  ubuntu-latest
    steps:
      - name: First step
        run: echo "First step"
      - name: second step
        run: echo "Second step"
  python_example:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Download the code
        uses: actions/checkout@v3
      - name: Run python code
        run: python test.py
      - name: Listing file
        run: ls /
      - name: print current wrk dir
        run: pwd
      - name: Python location
        run: ls $(pwd)
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: python_files
          path: test.py
  download_art:
    needs: python_example
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
      - name: List contents of the directory
        run: ls $(pwd)
      - name: run after downloading artifacts
        run: python test.py
  
        
