name: workflow_example
on: workflow_dispatch
jobs:
  first_job:
    runs-on:  ubuntu-latest
    steps:
      - name: First step
        run: echo "First step"
      - name: second step
        run: echo "Second step"
  python_example:
    needs: first_job
    runs-on: ubuntu-latest
    outputs:
      valuez: ${{ steps.vlaz.outputs.valuez}}
    steps:
      - name: Download the code
        uses: actions/checkout@v3
      - name: Run python code
        run: python test.py
      - name: Listing file
        run: ls /
      - name: print current wrk dir
        run: pwd
      - name: Python location
        run: ls $(pwd)
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: python_files
          path: test.py
      - name: pass_value
        id: vlaz
        run: echo 'valuez={Test}' >> ${{GITHUB_OUTPUT}} ';'
  download_art:
    needs: python_example
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
      - name: List contents of the directory
        run: cd python_files && ls / && python test.py
      - name: run after downloading artifacts
        run: python test.py
      - name: Getting the data
        run: echo "${{ needs.python_example.outputs.valuez}}"
  
        
